#!/usr/bin/env node
/**
 * Social share card, built from the hero photograph.
 *
 * A link to a photographer's site that previews as a text-only card is a wasted
 * impression, so the card is the work: the hero, cropped to 1200×630, darkened
 * at the foot, with the name and role over it.
 *
 * Written to src/app/ where Next picks it up by filename for every route.
 * Regenerated by `npm run photos`, so swapping the hero swaps the card.
 */

import fs from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const SOURCE = path.join("photos-source", "hero");
const OUT_DIR = path.join("src", "app");
const W = 1200;
const H = 630;

const site = JSON.parse(
  // Pull the strings straight out of site.ts so the card cannot drift from it.
  JSON.stringify({
    name: /name:\s*"([^"]+)"/.exec(await fs.readFile("src/data/site.ts", "utf8"))?.[1] ?? "",
    role: /role:\s*"([^"]+)"/.exec(await fs.readFile("src/data/site.ts", "utf8"))?.[1] ?? "",
    city: /city:\s*"([^"]+)"/.exec(await fs.readFile("src/data/site.ts", "utf8"))?.[1] ?? "",
  }),
);

const files = (await fs.readdir(SOURCE)).filter((f) => /\.(jpe?g|png|tiff?|webp)$/i.test(f));
if (files.length === 0) {
  console.error(`No hero photograph in ${SOURCE}/ — skipping the share card.`);
  process.exit(0);
}

const hero = path.join(SOURCE, files[0]);
const escape = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

const overlay = Buffer.from(`<svg width="${W}" height="${H}" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="fade" x1="0" y1="0" x2="0" y2="1">
      <stop offset="35%" stop-color="#000" stop-opacity="0"/>
      <stop offset="100%" stop-color="#000" stop-opacity="0.82"/>
    </linearGradient>
  </defs>
  <rect width="${W}" height="${H}" fill="url(#fade)"/>
  <text x="64" y="${H - 104}" fill="#FAFAFA" font-family="Helvetica, Arial, sans-serif"
        font-size="60" font-weight="600" letter-spacing="-1.4">${escape(site.name)}</text>
  <text x="64" y="${H - 56}" fill="#D4D4D8" font-family="Helvetica, Arial, sans-serif"
        font-size="25" letter-spacing="2.6">${escape(`${site.role} · ${site.city}`.toUpperCase())}</text>
</svg>`);

const card = await sharp(hero)
  .autoOrient()
  .resize(W, H, { fit: "cover", position: "attention" })
  .composite([{ input: overlay, top: 0, left: 0 }])
  .jpeg({ quality: 86, mozjpeg: true })
  .toBuffer();

// Metadata is stripped here too — the same privacy rule as every derivative.
const meta = await sharp(card).metadata();
if (meta.exif || meta.iptc || meta.xmp) {
  console.error("Metadata survived into the share card. Build stopped.");
  process.exit(1);
}

// Only one file: X and every other scraper fall back to og:image when no
// twitter:image is present, so a second identical 200KB copy earns nothing.
await fs.writeFile(path.join(OUT_DIR, "opengraph-image.jpg"), card);
console.log(
  `  share card  ${W}×${H}  ${(card.length / 1024).toFixed(0)}KB  → src/app/opengraph-image.jpg`,
);

/**
 * Favicon, from the same name. An SVG rather than a bitmap: a few hundred bytes,
 * sharp at every size, and it follows site.ts like everything else here.
 */
const initials = site.name
  .split(/\s+/)
  .filter(Boolean)
  .slice(0, 2)
  .map((w) => w[0].toUpperCase())
  .join("");

const icon = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
  <rect width="64" height="64" rx="8" fill="#171717"/>
  <text x="32" y="44" text-anchor="middle" fill="#FAFAFA"
        font-family="Helvetica, Arial, sans-serif" font-size="30"
        font-weight="600" letter-spacing="-1">${initials}</text>
</svg>
`;
await fs.writeFile(path.join(OUT_DIR, "icon.svg"), icon);
console.log(`  favicon     ${initials}  ${icon.length}B  → src/app/icon.svg`);
